### ISSUE TITLE
Sandboxed Decryption

### ISSUE THREAD

**Issue by winhowes** [winhowes/grd.me#33]
We should have a mode which isolates the decrypted text from the page to prevent malicious JS from reading the decrypted text yet without significantly impacting the page's usability or the decrypted text's appearance.

**Comment by winhowes** [comment]
Implemented on Firefox (toggled off by default).  Only thing left on FF would be to securely (as in no xss) get the @font-face css properties copied into the `iframe` to keep the decrypted text's look consistent.

**Comment by arnottcr** [comment]
I can confirm that this works on firefox up to version 39, but does not work on with e10s; e10s has only been tested on v39, as it is only enabled in nightly, not beta, aurora or dev, so yeah. logging forthcoming

**Comment by winhowes** [comment]
This should now work with e10s, but need confirmation. I'm also adding a performance label because though it is implemented, performance is still pretty poor on sites with multiple ciphertexts. What do you think about adding a mode where you have to click to decrypt a message - that way only one message is being decrypted at a time for better performance? If we do this, it may be a FF only feature

**Comment by arnottcr** [comment]
I like the concept of the selective decryption, if you do it I would suggest billing it as a privacy/security feature, as it kind of is.

Also, as of today's build firefox-nightly v39.0, running with [$ cfx  --e10s -b /bin/firefox-nightly run ], the secure decryption is still not working; there is improvement, as it now correctly identifies undecipherable cyphertext, but still hangs on decryptable text.

**Comment by arnottcr** [comment]
also, no issues with non e10s: sandboxed decryption fully functional, albeit it slower

**Comment by winhowes** [comment]
Hmm, I'll review sometime over the next 5 days

**Comment by winhowes** [comment]
Weird, yeah when e10s enabled, the scripts don't attach to the generated frame. But there's no errors..

**Comment by winhowes** [comment]
The actual implementation of this works, but each browser has different issues with this, so I'm gonna make two new tickets for those issues but close this one.

**Comment by arnottcr** [comment]
awesome; np with the close

**Comment by urandom2** [comment]
This issue was moved to GrdMe/GrdMe#38
